server:
  port: 8081

spring:

  profiles:
    include:
      - key
      - real-db

  jpa:
    properties:
      hibernate:
        dialect:
          - org.hibernate.dialect.MySQL57Dialect
          - storage_engine: innodb

  session:
    store-type: jdbc
